name: Production deploy to Heroku
on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Schedule UI Production Deploy
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    env:
      VITE_API_URL: "https://gpp-schedule-prod.herokuapp.com/graphql"
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v3
      # Update the version in src/version.json
      - name: Set version tag
        run: sed -i "s/development/$(date +'%Y%m%d')_$(echo $GITHUB_SHA | cut -c1-7)/" src/version.json
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
      - name: Build, Push and Release a Docker container to Heroku.
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          # Below you must provide variables for your Heroku app.

          # The email address associated with your Heroku account.
          # If you don't want to use repository secrets (which is recommended) you can do:
          # email: my.email@example.com
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

          # Heroku API key associated with provided user's email.
          # Api Key is available under your Heroku account settings.
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

          # Name of the heroku application to which the build is to be sent.
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_PROD }}
          buildpack: heroku-community/nginx
